CREATE DATABASE DB_CONSTRUINDO_VIDAS;
USE DB_CONSTRUINDO_VIDAS;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(255) NOT NULL,
PARTE VARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
MARCA VARCHAR(255) NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO DECIMAL (6,2) NOT NULL,
CATEGORIAS_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY(CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS(TIPO,PARTE)
VALUES("ALVENARIA","ESTRUTURA");
INSERT INTO TB_CATEGORIAS(TIPO,PARTE)
VALUES("ELETRICA","ESTRUTURA");
INSERT INTO TB_CATEGORIAS(TIPO,PARTE)
VALUES("ELETRICA","DECORAÇÃO");
INSERT INTO TB_CATEGORIAS(TIPO,PARTE)
VALUES("HIDRAULICA","ESTRUTURA");
INSERT INTO TB_CATEGORIAS(TIPO,PARTE)
VALUES("HIDRAULICA","DECORAÇÃO");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PRODUTOS(NOME,MARCA,QUANTIDADE,PRECO,CATEGORIAS_ID)
VALUES("CIMENTO","VOTORAN",300,35.00,1);
INSERT INTO TB_PRODUTOS(NOME,MARCA,QUANTIDADE,PRECO,CATEGORIAS_ID)
VALUES("LÂMPADA LED","ELGIN",500,20.00,3);
INSERT INTO TB_PRODUTOS(NOME,MARCA,QUANTIDADE,PRECO,CATEGORIAS_ID)
VALUES("CAIXA DE LUZ","TIGRE",600,4.00,2);
INSERT INTO TB_PRODUTOS(NOME,MARCA,QUANTIDADE,PRECO,CATEGORIAS_ID)
VALUES("COTOVELO 3/4","TIGRE",800,9.00,4);
INSERT INTO TB_PRODUTOS(NOME,MARCA,QUANTIDADE,PRECO,CATEGORIAS_ID)
VALUES("ARGAMASSA","BAUTECH",300,50.00,1);
INSERT INTO TB_PRODUTOS(NOME,MARCA,QUANTIDADE,PRECO,CATEGORIAS_ID)
VALUES("MISTURADOR","DECA",200,200.00,5);
INSERT INTO TB_PRODUTOS(NOME,MARCA,QUANTIDADE,PRECO,CATEGORIAS_ID)
VALUES("ACABAMENTO PARA REGISTRO DE PRESSÃO","DOCOL",100,80.00,5);
INSERT INTO TB_PRODUTOS(NOME,MARCA,QUANTIDADE,PRECO,CATEGORIAS_ID)
VALUES("SIFÃO RÍGIDO","DOCOL",100,140.00,5);

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 100.00;
SELECT * FROM TB_PRODUTOS WHERE PRECO > 70.00 AND PRECO < 150.00;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON
TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON
TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID WHERE CATEGORIAS_ID=1;

