CREATE DATABASE DB_CIDADE_DOS_VEGETAIS;
USE DB_CIDADE_DOS_VEGETAIS;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(255) NOT NULL,
VARIEDADE VARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO DECIMAL (6,2) NOT NULL,
MEDIDA VARCHAR(255) NOT NULL,
CATEGORIAS_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY(CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS(TIPO,VARIEDADE)
VALUES("ORGÂNICO","VEGETAL");
INSERT INTO TB_CATEGORIAS(TIPO,VARIEDADE)
VALUES("CONVENCIONAL","VEGETAL");
INSERT INTO TB_CATEGORIAS(TIPO,VARIEDADE)
VALUES("ORGÂNICO","LEGUME");
INSERT INTO TB_CATEGORIAS(TIPO,VARIEDADE)
VALUES("CONVENCIONAL","LEGUME");
INSERT INTO TB_CATEGORIAS(TIPO,VARIEDADE)
VALUES("ORGÂNICO","FRUTA");
INSERT INTO TB_CATEGORIAS(TIPO,VARIEDADE)
VALUES("CONVENCIONAL","FRUTA");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PRODUTOS(NOME,QUANTIDADE,PRECO,MEDIDA,CATEGORIAS_ID)
VALUES("LARANJA",200,4.00,"KG",6);
INSERT INTO TB_PRODUTOS(NOME,QUANTIDADE,PRECO,MEDIDA,CATEGORIAS_ID)
VALUES("MEXERICA",100,6.00,"KG",5);
INSERT INTO TB_PRODUTOS(NOME,QUANTIDADE,PRECO,MEDIDA,CATEGORIAS_ID)
VALUES("BATATA",300,3.00,"KG",4);
INSERT INTO TB_PRODUTOS(NOME,QUANTIDADE,PRECO,MEDIDA,CATEGORIAS_ID)
VALUES("PEPINO",400,4.00,"KG",3);
INSERT INTO TB_PRODUTOS(NOME,QUANTIDADE,PRECO,MEDIDA,CATEGORIAS_ID)
VALUES("ALFACE",200,1.00,"UN",1);
INSERT INTO TB_PRODUTOS(NOME,QUANTIDADE,PRECO,MEDIDA,CATEGORIAS_ID)
VALUES("RÚCULA",100,0.90,"UN",2);
INSERT INTO TB_PRODUTOS(NOME,QUANTIDADE,PRECO,MEDIDA,CATEGORIAS_ID)
VALUES("MANGA",500,6.00,"KG",5);
INSERT INTO TB_PRODUTOS(NOME,QUANTIDADE,PRECO,MEDIDA,CATEGORIAS_ID)
VALUES("MAÇÃ",300,3.00,"KG",6);

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 5.00;
SELECT * FROM TB_PRODUTOS WHERE PRECO > 2.00 AND PRECO < 5.00;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%E%";

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON
TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON
TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID WHERE CATEGORIAS_ID=3 OR CATEGORIAS_ID=4;

