CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(255) NOT NULL,
TAMANHO VARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT AUTO_INCREMENT,
SABOR VARCHAR(255) NOT NULL,
MASSA VARCHAR(255) NOT NULL,
BORDA VARCHAR(255) NOT NULL,
PRECO DECIMAL (6,2) NOT NULL,
CATEGORIAS_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY(CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS(TIPO,TAMANHO)
VALUES("SALGADA","BROTINHO");
INSERT INTO TB_CATEGORIAS(TIPO,TAMANHO)
VALUES("SALGADA","TRADICIONAL");
INSERT INTO TB_CATEGORIAS(TIPO,TAMANHO)
VALUES("SALGADA","FAMÍLIA");
INSERT INTO TB_CATEGORIAS(TIPO,TAMANHO)
VALUES("DOCE","BROTINHO");
INSERT INTO TB_CATEGORIAS(TIPO,TAMANHO)
VALUES("DOCE","TRADICIONAL");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PIZZAS(SABOR,MASSA,BORDA,PRECO,CATEGORIAS_ID)
VALUES("MUSSARELA","FINA","RECHEADA",40.00,2);
INSERT INTO TB_PIZZAS(SABOR,MASSA,BORDA,PRECO,CATEGORIAS_ID)
VALUES("CALABRESA","FINA","RECHEADA",40.00,2);
INSERT INTO TB_PIZZAS(SABOR,MASSA,BORDA,PRECO,CATEGORIAS_ID)
VALUES("MUSSARELA","FINA","RECHEADA",55.00,3);
INSERT INTO TB_PIZZAS(SABOR,MASSA,BORDA,PRECO,CATEGORIAS_ID)
VALUES("CALABRESA","FINA","RECHEADA",55.00,3);
INSERT INTO TB_PIZZAS(SABOR,MASSA,BORDA,PRECO,CATEGORIAS_ID)
VALUES("MUSSARELA","FINA","RECHEADA",30.00,1);
INSERT INTO TB_PIZZAS(SABOR,MASSA,BORDA,PRECO,CATEGORIAS_ID)
VALUES("CALABRESA","FINA","RECHEADA",30.00,1);
INSERT INTO TB_PIZZAS(SABOR,MASSA,BORDA,PRECO,CATEGORIAS_ID)
VALUES("CHOCOLATE COM MORANGO","FINA","RECHEADA",50.00,5);
INSERT INTO TB_PIZZAS(SABOR,MASSA,BORDA,PRECO,CATEGORIAS_ID)
VALUES("CHOCOLATE COM MORANGO","FINA","RECHEADA",35.00,4);

SELECT * FROM TB_PIZZAS;

SELECT * FROM TB_PIZZAS WHERE PRECO < 45.00;
SELECT * FROM TB_PIZZAS WHERE PRECO < 50.00 AND PRECO < 100.00;
SELECT * FROM TB_PIZZAS WHERE SABOR LIKE "%M%";

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON
TB_PIZZAS.CATEGORIAS_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON
TB_PIZZAS.CATEGORIAS_ID = TB_CATEGORIAS.ID WHERE CATEGORIAS_ID=4 OR CATEGORIAS_ID=5;


