CREATE DATABASE SERVICO_RH;

USE SERVICO_RH;

CREATE TABLE TB_COLABORADORES(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT,
GENERO CHAR(255),
RACA CHAR(255),
CIDADE CHAR(255),
PRIMARY KEY (ID)
);

ALTER TABLE TB_COLABORADORES DROP RACA;
ALTER TABLE TB_COLABORADORES DROP CIDADE;

ALTER TABLE TB_COLABORADORES ADD INGRESSO DATE;
ALTER TABLE TB_COLABORADORES ADD SALARIO DECIMAL;

INSERT INTO TB_COLABORADORES (NOME,IDADE,GENERO,INGRESSO,SALARIO)
VALUES ("ALEXANDRA REIS",46,"FEMININO","2022-09-23",1900.00);
INSERT INTO TB_COLABORADORES (NOME,IDADE,GENERO,INGRESSO,SALARIO)
VALUES ("SILVIA SANTANA",29,"FEMININO","2022-09-24",2100.00);
INSERT INTO TB_COLABORADORES (NOME,IDADE,GENERO,INGRESSO,SALARIO)
VALUES ("LETICIA ZANOTTI",28,"FEMININO","2022-09-25",1800.00);
INSERT INTO TB_COLABORADORES (NOME,IDADE,GENERO,INGRESSO,SALARIO)
VALUES ("STEPHANY SOUZA",26,"FEMININO","2022-09-26",2500.00);
INSERT INTO TB_COLABORADORES (NOME,IDADE,GENERO,INGRESSO,SALARIO)
VALUES ("ALINE SASSAKI",28,"FEMININO","2022-09-27",3000.00);

SELECT * FROM TB_COLABORADORES;

ALTER TABLE TB_COLABORADORES MODIFY SALARIO DECIMAL (6,2);

SELECT * FROM TB_COLABORADORES WHERE SALARIO > 2000.00;
SELECT * FROM TB_COLABORADORES WHERE SALARIO < 2000.00;

