CREATE DATABASE DB_ESCOLA;
USE DB_ESCOLA;

CREATE TABLE TB_ALUNOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
RA INT,
TURMA VARCHAR(255),
DISCIPLINA VARCHAR(255),
NOTA DECIMAL (2,1),
PRIMARY KEY(ID)
);

INSERT INTO TB_ALUNOS(NOME,RA,TURMA,DISCIPLINA,NOTA)
VALUES ("ALINE",123456,"3A","MATEMÁTICA",8.00);
INSERT INTO TB_ALUNOS(NOME,RA,TURMA,DISCIPLINA,NOTA)
VALUES ("BRUNA",234567,"3A","MATEMÁTICA",5.00);
INSERT INTO TB_ALUNOS(NOME,RA,TURMA,DISCIPLINA,NOTA)
VALUES ("CAMILA",345678,"3A","MATEMÁTICA",7.50);
INSERT INTO TB_ALUNOS(NOME,RA,TURMA,DISCIPLINA,NOTA)
VALUES ("DEBORA",456789,"3A","MATEMÁTICA",10.00);
INSERT INTO TB_ALUNOS(NOME,RA,TURMA,DISCIPLINA,NOTA)
VALUES ("ELIANE",567890,"3A","MATEMÁTICA",9.50);
INSERT INTO TB_ALUNOS(NOME,RA,TURMA,DISCIPLINA,NOTA)
VALUES ("FLAVIA",678901,"3A","MATEMÁTICA",4.50);
INSERT INTO TB_ALUNOS(NOME,RA,TURMA,DISCIPLINA,NOTA)
VALUES ("GABRIELA",789012,"3A","MATEMÁTICA",6.50);
INSERT INTO TB_ALUNOS(NOME,RA,TURMA,DISCIPLINA,NOTA)
VALUES ("HELENA",890123,"3A","MATEMÁTICA",8.50);

SELECT * FROM TB_ALUNOS;
SELECT * FROM TB_ALUNOS WHERE NOTA > 7.00;
SELECT * FROM TB_ALUNOS WHERE NOTA < 7.00;